services:
  fastp:
    build:
      context: ./fastp
    container_name: fastp
    volumes:
      - ./fastp:/data
    working_dir: /data
    command: ["bash"]
    stdin_open: true
    tty: true

  multiqc:
    build:
      context: ./multiqc
    container_name: multiqc
    volumes:
      - ./multiqc:/data
    working_dir: /data
    command: ["bash"]
    stdin_open: true
    tty: true

  star:
    build:
      context: ./star
    container_name: star
    volumes:
      - ./star:/data
    working_dir: /data
    command: ["bash"]
    stdin_open: true
    tty: true

  featurecounts:
    build:
      context: ./subread
    container_name: subread
    volumes:
      - ./subread:/data
    working_dir: /data
    command: ["bash"]
    stdin_open: true
    tty: true

  trimmomatic:
    build:
      context: ./trimmomatic
    container_name: trimmomatic
    volumes:
      - ./trimmomatic:/data
    working_dir: /data
    command: ["bash"]
    stdin_open: true
    tty: true

  seqtk:
    build:
      context: ./seqtk
    container_name: seqtk
    volumes:
      - ./seqtk:/data
    working_dir: /data
    command: ["bash"]
    stdin_open: true
    tty: true
